#!/bin/sh
set -eu

# Usage: buildcore thumbulator mecrisp-stellaris-binary forth-source precompiled-binary

stty -icanon -echo

{
   echo "compiletoflash"
   cat "$3"
   echo 'compiletoflash here hex DABBAD00 !'
   # cat -
} | "$1" "$2"

stty sane

echo

mkdir -p "$(dirname "$4")"
mv coredump.bin "$4"
