#!/bin/bash

gcc -o thumbulator-aducm4050        -O2 thumbulator-aducm4050.c
gcc -o thumbulator-lm4f120-tm4c1294 -O2 thumbulator-lm4f120-tm4c1294.c
gcc -o thumbulator-stm32f051        -O2 thumbulator-stm32f051.c
gcc -o thumbulator-stm32f103        -O2 thumbulator-stm32f103.c
gcc -o thumbulator-stm32f303        -O2 thumbulator-stm32f303.c
gcc -o thumbulator-stm32l053        -O2 thumbulator-stm32l053.c
gcc -o thumbulator-stm32g031        -O2 thumbulator-stm32g031.c
gcc -o thumbulator-numworks         -O2 thumbulator-numworks.c
gcc -o thumbulator-palanqin         -O2 thumbulator-palanqin.c
gcc -o thumbulator-lpc845m301       -O2 thumbulator-lpc845m301.c
gcc -o thumbulator-rp2040           -O2 thumbulator-rp2040.c
