#!/bin/bash
arm-linux-gnueabi-as -o mecrisp-stellaris-linux.o mecrisp-stellaris-linux.s && arm-linux-gnueabi-ld -T mecrisp.ld -z max-page-size=4096 -o mecrisp-stellaris-linux mecrisp-stellaris-linux.o
