#!/bin/bash

# With disassembler and math

stty -icanon -echo

{
   echo -e "compiletoflash\n"
   cat ../common/fixpt-math-lib.fs
   cat ../common/disassembler-m3.txt
   cat save.txt
   echo -e "save\" mecrisp-stellaris-linux-with-disassembler-and-math\n"
   # cat -
} | ./mecrisp-stellaris-linux

stty sane

echo -e ""

# With VIS

stty -icanon -echo

{
   echo -e "compiletoflash\n"
   cat ../common/VIS/vis-0.8.4.2-mecrisp-stellaris.fs
   echo -e "compiletoflash\n"
   cat ../common/VIS/vis-0.8.4-disassembler-m3.fs
   echo -e "compiletoram\n"
   cat save.txt
   echo -e "save\" mecrisp-stellaris-linux-vis\n"
   # cat -
} | qemu-arm-static mecrisp-stellaris-linux

stty sane

echo -e ""
