#!/bin/sh
set -eu

# With disassembler and math

stty -icanon -echo

{
   echo "compiletoflash"
   cat ../common/fixpt-math-lib.fs
   cat ../common/disassembler-m3.txt
   cat save.txt
   echo 'save" mecrisp-stellaris-linux-with-disassembler-and-math'
   # cat -
} | qemu-arm-static mecrisp-stellaris-linux

stty sane

echo

# With VIS

stty -icanon -echo

{
   echo "compiletoflash"
   cat ../common/VIS/vis-0.8.4.2-mecrisp-stellaris.fs
   echo "compiletoflash"
   cat ../common/VIS/vis-0.8.4-disassembler-m3.fs
   echo "compiletoram"
   cat save.txt
   echo 'save" mecrisp-stellaris-linux-vis'
   # cat -
} | qemu-arm-static mecrisp-stellaris-linux

stty sane

echo
