#!/bin/sh
set -eu

# Usage: buildcore thumbulator mecrisp-stellaris-binary forth-source precompiled-binary

stty -icanon -echo

{
   echo "compiletoflash"
   cat "$3"
   echo "compiletoflash hex 20000 DABBAD00 !"
   # echo "compiletoflash hex 10000 DABBAD00 !"
   # cat -
} | "$1" "$2"

stty sane

echo

mv coredump.bin "$4"
