#!/bin/sh
set -eu

build() {
	(
		port="${1:?}"
		cd "${port:?}"

		mkdir -p "../../${port:?}"
		make clean all

		set -- *.bin
		if [ -f "$1" ]; then
			ls -l -- "$@"
			md5sum -- "$@"
			cp -- "$@" "../../${port:?}/"
		fi

		set -- *.hex
		if [ -f "$1" ]; then
			cp -- "$@" "../../${port:?}/"
		fi

		set -- *.srec
		if [ -f "$1" ]; then
			cp -- "$@" "../../${port:?}/"
		fi

	)
}

build aducm4050-ra
build atsame70-ra
build lpc1114fn28
build lpc1114fn28-ra
build lpc1114fbd48
build lpc1114fbd48-ra
build lpc1115fbd48
build lpc1115fbd48-ra
build lpc845m301
build kl25z128
build kl25z128-ra
build kl46z256
build kl46z256-ra
build mk20dx256
build mk64fn1m0
build mk64fn1m0-ra
build nrf51822
build nrf52832
build microbit
build microbit-ra
build microbit-v2
build microbit-v2-ra
build msp432p401r
build msp432p401r-ra
build lm3s811-ra
build lm4f120
build lm4f120-ra
build lm4f232
build palanqin
build palanqin-ra
build tm4c1294
build tm4c1294-ra
build stm32f030f4
build stm32f030k6
build stm32f030k6-ra
build stm32f030r8
build stm32f030r8-ra
build stm32f042f6
build stm32f042f6-ra
build stm32f051
build stm32f051-ra
build stm32f072rb
build stm32f072rb-ra
build stm32l031k6
build stm32l053c8
build stm32l053c8-ra
build stm32l073rz
build stm32l073rz-ra
build stm32l082kz-ra
build stm32l152
build stm32l152rb
build stm32l432-ra
build stm32f100
build stm32f103
build stm32f103-ra
build stm32f103rb
build stm32f103rb-ra
build stm32f207zg
build stm32f207zg-ra
build stm32f303
build stm32f303-ra
build stm32f303k8
build stm32f303k8-ra
build stm32f303re-ra
build stm32f401
build stm32f401-ra
build stm32f401cc
build stm32f401cc-ra
build stm32f401cd-ra
build stm32f407
build stm32f407-ra
build stm32f407diymore
build stm32f407diymore-ra
build stm32f411
build stm32f411-ra
build stm32f429
build stm32l476
build stm32l476-ra
build stm32f746-ra
build stm32f767-ra
build stm32h743-ra
build stm32g031f4
build stm32g031f6-ra
build stm32g031f8-ra
build stm32g031j6-ra
build stm32g071rb-ra
build stm32g431kb-ra
build stm32wb55
build numworks-ra
build xmc1100
build xmc1100-ra
build efm32gg990
build efm32gg990-ra
build efm32hg322
build efm32hg322-ra
build cy8c4245axi
build cy8c5888
build nuc123
build nuc123-ra

cd rp2040-ra
./assemble
cp *.bin ../../rp2040-ra
cp    blinky-boot/*crc.bin ../../rp2040-ra/tools
cp launchpad-boot/*crc.bin ../../rp2040-ra/tools
cd ..

# Intel Hex images for STM targets:

cd ..

cd stm32f030f4
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f030f4.bin mecrisp-stellaris-stm32f030f4.hex
cd ..

cd stm32f030k6
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f030k6.bin mecrisp-stellaris-stm32f030k6.hex
cd ..

cd stm32f030k6-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f030k6.bin mecrisp-stellaris-stm32f030k6.hex
cd ..

cd stm32f030r8
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f030r8.bin mecrisp-stellaris-stm32f030r8.hex
cd ..

cd stm32f030r8-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f030r8.bin mecrisp-stellaris-stm32f030r8.hex
cd ..

cd stm32f042f6
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f042f6.bin mecrisp-stellaris-stm32f042f6.hex
cd ..

cd stm32f042f6-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f042f6.bin mecrisp-stellaris-stm32f042f6.hex
cd ..

cd stm32f051
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f051.bin mecrisp-stellaris-stm32f051.hex
cd ..

cd stm32f051-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f051.bin mecrisp-stellaris-stm32f051.hex
cd ..

cd stm32f072rb
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f072rb.bin mecrisp-stellaris-stm32f072rb.hex
cd ..

cd stm32f072rb-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f072rb.bin mecrisp-stellaris-stm32f072rb.hex
cd ..

cd stm32l031k6
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32l031k6.bin mecrisp-stellaris-stm32l031k6.hex
cd ..

cd stm32l053c8
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32l053c8.bin mecrisp-stellaris-stm32l053c8.hex
cd ..

cd stm32l053c8-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32l053c8.bin mecrisp-stellaris-stm32l053c8.hex
cd ..

cd stm32l073rz
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32l073rz.bin mecrisp-stellaris-stm32l073rz.hex
cd ..

cd stm32l073rz-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32l073rz.bin mecrisp-stellaris-stm32l073rz.hex
cd ..

cd stm32l082kz-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32l082kz.bin mecrisp-stellaris-stm32l082kz.hex
cd ..

cd stm32l152
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32l152.bin mecrisp-stellaris-stm32l152.hex
cd ..

cd stm32l152rb
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32l152rb.bin mecrisp-stellaris-stm32l152rb.hex
cd ..

cd stm32l432-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32l432.bin mecrisp-stellaris-stm32l432.hex
cd ..

cd stm32f100
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f100.bin mecrisp-stellaris-stm32f100.hex
cd ..

cd stm32f103
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f103.bin mecrisp-stellaris-stm32f103.hex
cd ..

cd stm32f103-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f103.bin mecrisp-stellaris-stm32f103.hex
cd ..

cd stm32f103rb
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f103rb.bin mecrisp-stellaris-stm32f103rb.hex
cd ..

cd stm32f103rb-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f103rb.bin mecrisp-stellaris-stm32f103rb.hex
cd ..

cd stm32f207zg
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f207zg.bin mecrisp-stellaris-stm32f207zg.hex
cd ..

cd stm32f207zg-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f207zg.bin mecrisp-stellaris-stm32f207zg.hex
cd ..

cd stm32f303
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f303.bin mecrisp-stellaris-stm32f303.hex
cd ..

cd stm32f303-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f303.bin mecrisp-stellaris-stm32f303.hex
cd ..

cd stm32f303k8
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f303k8.bin mecrisp-stellaris-stm32f303k8.hex
cd ..

cd stm32f303k8-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f303k8.bin mecrisp-stellaris-stm32f303k8.hex
cd ..

cd stm32f303re-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f303re.bin mecrisp-stellaris-stm32f303re.hex
cd ..

cd stm32f401
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f401.bin mecrisp-stellaris-stm32f401.hex
cd ..

cd stm32f401-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f401.bin mecrisp-stellaris-stm32f401.hex
cd ..

cd stm32f401cd-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f401cd.bin mecrisp-stellaris-stm32f401cd.hex
cd ..

cd stm32f407
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f407.bin mecrisp-stellaris-stm32f407.hex
cd ..

cd stm32f407-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f407.bin mecrisp-stellaris-stm32f407.hex
cd ..

cd stm32f407diymore
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f407diymore.bin mecrisp-stellaris-stm32f407diymore.hex
cd ..

cd stm32f407diymore-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f407diymore.bin mecrisp-stellaris-stm32f407diymore.hex
cd ..

cd stm32f411
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f411.bin mecrisp-stellaris-stm32f411.hex
cd ..

cd stm32f411-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f411.bin mecrisp-stellaris-stm32f411.hex
cd ..

cd stm32f429
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32f429.bin mecrisp-stellaris-stm32f429.hex
cd ..

cd stm32l476
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32l476.bin mecrisp-stellaris-stm32l476.hex
cd ..

cd stm32l476-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32l476.bin mecrisp-stellaris-stm32l476.hex
cd ..

cd stm32g031f4
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32g031f4.bin mecrisp-stellaris-stm32g031f4.hex
cd ..

cd stm32g031f6-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32g031f6.bin mecrisp-stellaris-stm32g031f6.hex
cd ..

cd stm32g031f8-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32g031f8.bin mecrisp-stellaris-stm32g031f8.hex
cd ..

cd stm32g031j6-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32g031j6.bin mecrisp-stellaris-stm32g031j6.hex
cd ..

cd stm32g071rb-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32g071rb.bin mecrisp-stellaris-stm32g071rb.hex
cd ..

cd stm32g431kb-ra
arm-none-eabi-objcopy --change-addresses 0x08000000 -I binary -O ihex mecrisp-stellaris-stm32g431kb.bin mecrisp-stellaris-stm32g431kb.hex
cd ..

# Special target for running on ARM Linux and Android:

cd mecrisp-stellaris-source

cd linux
./assemble
cp mecrisp-stellaris-linux ../../linux
cd ..

cd linux-ra
./assemble
cp mecrisp-stellaris-linux ../../linux-ra
cd ..

cd freebsd-ra
./assemble
cp mecrisp-stellaris-freebsd       ../../freebsd-ra
cp mecrisp-stellaris-freebsd-armv6 ../../freebsd-ra
cd ..

