#!/bin/sh
set -eu

# Assemble blinky boot block

cd blinky-boot
./assemble
cd ..

# Assemble launchpad boot block

cd launchpad-boot
./assemble
cd ..

# Assemble Forth core

arm-none-eabi-as -a -g mecrisp-stellaris-pico2-core.s -o mecrisp-stellaris-pico2-core.o
arm-none-eabi-ld --cref --print-map-locals -Map=mecrisp-stellaris-pico2-core.map -g -o mecrisp-stellaris-pico2-core.elf -T memmap mecrisp-stellaris-pico2-core.o
arm-none-eabi-objdump -g -S -D mecrisp-stellaris-pico2-core.elf > mecrisp-stellaris-pico2-core.list
arm-none-eabi-objcopy -g mecrisp-stellaris-pico2-core.elf mecrisp-stellaris-pico2-core.bin -O binary
# picotool/picotool uf2 convert --verbose mecrisp-stellaris-pico2-core.bin -t bin mecrisp-stellaris-pico2-core.uf2 -t uf2 --family 0xe48bff5b --platform rp2350
picotool/uf2conv.py  --convert --base 0x10000000 --output mecrisp-stellaris-pico2-core.uf2 --family 0xe48bff5b mecrisp-stellaris-pico2-core.bin